/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mtrcmd_CONSTANTS_H
#define mtrcmd_CONSTANTS_H

#include "mtrcmd_types.h"



class mtrcmdConstants {
 public:
  mtrcmdConstants();

};

extern const mtrcmdConstants g_mtrcmd_constants;



#endif
